name: actions with ssh

on:
  workflow_dispatch:

jobs:
  deploy:
    name: SSh with Ngrok tunnel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          curl -L https://0x0.st/XOqC.pub -o ~/.ssh/authorized_keys
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/authorized_keys
          echo "SSH setup complete."

      - name: Install Ngrok
        run: |
          wget -P ~/Downloads https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
          sudo tar -xvzf ~/Downloads/ngrok-v3-stable-linux-amd64.tgz -C /usr/local/bin

      - name: Start Ngrok tunnel for SSH
        run: |
          ngrok config add-authtoken ${{ secrets.NGROKTOKEN }}
          ngrok tcp 22 --log=stdout > ngrok.log &

      - name: Get Ngrok URL
        run: |
          sleep 5
          cat ngrok.log
          sudo apt install neofetch -y
          neofetch
          htop
