name: actions with ssh

on:
  workflow_dispatch:

jobs:
  deploy:
    name: SSh with Ngrok tunnel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          sudo apt install tmate -y
          tmate > tmate.log &
          cat tmate.log

      - name: showing server info
        run: |
          sleep 5
          sudo apt install neofetch -y
          neofetch

      - name: Keep the job active
        run: sleep $((14 * 24 * 60 * 60))
