name: coustom tmate
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        run: |
          sudo apt install tmate -y
          tmate -F
