name: actions with ssh

on:
  workflow_dispatch:

jobs:
  deploy:
    name: SSh with Tmate tunnel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: mxschmitt/action-tmate@v3

      - name: extra step
        run: |
          cat tmate.log
          sleep 5
          sudo apt install neofetch -y
          neofetch

      - name: Keep the job active
        run: sleep $((14 * 24 * 60 * 60))
